// Code generated by cmd/codegen from types.gen.go's own constants. DO NOT EDIT.

package openapi

// ErrorCodeValues lists every valid ErrorCode, in the order oapi-codegen generated them.
var ErrorCodeValues = []ErrorCode{
	INTERNALERROR,
	NOTFOUND,
	PAYLOADTOOLARGE,
	RATELIMITED,
	UNAUTHORIZED,
	UNPROCESSABLE,
	UNSUPPORTEDMEDIATYPE,
	VALIDATIONERROR,
}

// QrDesignConfigBackground1Values lists every valid QrDesignConfigBackground1, in the order oapi-codegen generated them.
var QrDesignConfigBackground1Values = []QrDesignConfigBackground1{
	QrDesignConfigBackground1Transparent,
}

// QrDesignConfigErrorCorrectionValues lists every valid QrDesignConfigErrorCorrection, in the order oapi-codegen generated them.
var QrDesignConfigErrorCorrectionValues = []QrDesignConfigErrorCorrection{
	H,
	L,
	M,
	Q,
}

// QrDesignConfigFinderEyeColor1TypeValues lists every valid QrDesignConfigFinderEyeColor1Type, in the order oapi-codegen generated them.
var QrDesignConfigFinderEyeColor1TypeValues = []QrDesignConfigFinderEyeColor1Type{
	QrDesignConfigFinderEyeColor1TypeLinear,
	QrDesignConfigFinderEyeColor1TypeRadial,
}

// QrDesignConfigFinderFrameColor1TypeValues lists every valid QrDesignConfigFinderFrameColor1Type, in the order oapi-codegen generated them.
var QrDesignConfigFinderFrameColor1TypeValues = []QrDesignConfigFinderFrameColor1Type{
	QrDesignConfigFinderFrameColor1TypeLinear,
	QrDesignConfigFinderFrameColor1TypeRadial,
}

// QrDesignConfigFinderStyleIdValues lists every valid QrDesignConfigFinderStyleId, in the order oapi-codegen generated them.
var QrDesignConfigFinderStyleIdValues = []QrDesignConfigFinderStyleId{
	QrDesignConfigFinderStyleIdBlotchy,
	QrDesignConfigFinderStyleIdBrush,
	QrDesignConfigFinderStyleIdCarved,
	QrDesignConfigFinderStyleIdClassic,
	QrDesignConfigFinderStyleIdComic,
	QrDesignConfigFinderStyleIdDotted,
	QrDesignConfigFinderStyleIdDrip,
	QrDesignConfigFinderStyleIdEroded,
	QrDesignConfigFinderStyleIdLeaf,
	QrDesignConfigFinderStyleIdMeadow,
	QrDesignConfigFinderStyleIdModern,
	QrDesignConfigFinderStyleIdMorphing,
	QrDesignConfigFinderStyleIdPill,
	QrDesignConfigFinderStyleIdScribble,
	QrDesignConfigFinderStyleIdSegmented,
	QrDesignConfigFinderStyleIdShifted,
	QrDesignConfigFinderStyleIdSketchy,
	QrDesignConfigFinderStyleIdStamp,
	QrDesignConfigFinderStyleIdSticker,
	QrDesignConfigFinderStyleIdWobbly,
}

// QrDesignConfigHaloColorModeValues lists every valid QrDesignConfigHaloColorMode, in the order oapi-codegen generated them.
var QrDesignConfigHaloColorModeValues = []QrDesignConfigHaloColorMode{
	Inherit,
	Palette,
}

// QrDesignConfigHaloColorPaletteModeValues lists every valid QrDesignConfigHaloColorPaletteMode, in the order oapi-codegen generated them.
var QrDesignConfigHaloColorPaletteModeValues = []QrDesignConfigHaloColorPaletteMode{
	QrDesignConfigHaloColorPaletteModeCheckerboard,
	QrDesignConfigHaloColorPaletteModeDiagonal,
	QrDesignConfigHaloColorPaletteModeGroup,
	QrDesignConfigHaloColorPaletteModeHorizontal,
	QrDesignConfigHaloColorPaletteModeLava,
	QrDesignConfigHaloColorPaletteModeMandala,
	QrDesignConfigHaloColorPaletteModeNoise,
	QrDesignConfigHaloColorPaletteModeRadial,
	QrDesignConfigHaloColorPaletteModeRings,
	QrDesignConfigHaloColorPaletteModeScatter,
	QrDesignConfigHaloColorPaletteModeSpiral,
	QrDesignConfigHaloColorPaletteModeVertical,
	QrDesignConfigHaloColorPaletteModeWave,
}

// QrDesignConfigHaloCurveValues lists every valid QrDesignConfigHaloCurve, in the order oapi-codegen generated them.
var QrDesignConfigHaloCurveValues = []QrDesignConfigHaloCurve{
	QrDesignConfigHaloCurveEase,
	QrDesignConfigHaloCurveLinear,
	QrDesignConfigHaloCurveNone,
	QrDesignConfigHaloCurveSteep,
}

// QrDesignConfigHaloFalloffValues lists every valid QrDesignConfigHaloFalloff, in the order oapi-codegen generated them.
var QrDesignConfigHaloFalloffValues = []QrDesignConfigHaloFalloff{
	Round,
	Square,
	Squircle,
}

// QrDesignConfigHaloModeValues lists every valid QrDesignConfigHaloMode, in the order oapi-codegen generated them.
var QrDesignConfigHaloModeValues = []QrDesignConfigHaloMode{
	Composite,
	Unified,
}

// QrDesignConfigLogo0IdValues lists every valid QrDesignConfigLogo0Id, in the order oapi-codegen generated them.
var QrDesignConfigLogo0IdValues = []QrDesignConfigLogo0Id{
	QrDesignConfigLogo0IdAmazon,
	QrDesignConfigLogo0IdApple,
	QrDesignConfigLogo0IdBluesky,
	QrDesignConfigLogo0IdDiscord,
	QrDesignConfigLogo0IdEmail,
	QrDesignConfigLogo0IdEuro,
	QrDesignConfigLogo0IdFacebook,
	QrDesignConfigLogo0IdGithub,
	QrDesignConfigLogo0IdGoogle,
	QrDesignConfigLogo0IdGoogleplay,
	QrDesignConfigLogo0IdInstagram,
	QrDesignConfigLogo0IdKim,
	QrDesignConfigLogo0IdLinkedin,
	QrDesignConfigLogo0IdLocation,
	QrDesignConfigLogo0IdPaypal,
	QrDesignConfigLogo0IdPhone,
	QrDesignConfigLogo0IdPinterest,
	QrDesignConfigLogo0IdSnapchat,
	QrDesignConfigLogo0IdSpotify,
	QrDesignConfigLogo0IdSwissCross,
	QrDesignConfigLogo0IdTelegram,
	QrDesignConfigLogo0IdThreads,
	QrDesignConfigLogo0IdTiktok,
	QrDesignConfigLogo0IdTwitch,
	QrDesignConfigLogo0IdWebsite,
	QrDesignConfigLogo0IdWhatsapp,
	QrDesignConfigLogo0IdWifi,
	QrDesignConfigLogo0IdX,
	QrDesignConfigLogo0IdYoutube,
}

// QrDesignConfigLogo0ModeValues lists every valid QrDesignConfigLogo0Mode, in the order oapi-codegen generated them.
var QrDesignConfigLogo0ModeValues = []QrDesignConfigLogo0Mode{
	QrDesignConfigLogo0ModeClear,
	QrDesignConfigLogo0ModeFill,
	QrDesignConfigLogo0ModeFloat,
}

// QrDesignConfigLogo1ModeValues lists every valid QrDesignConfigLogo1Mode, in the order oapi-codegen generated them.
var QrDesignConfigLogo1ModeValues = []QrDesignConfigLogo1Mode{
	QrDesignConfigLogo1ModeClear,
	QrDesignConfigLogo1ModeFill,
	QrDesignConfigLogo1ModeFloat,
}

// QrDesignConfigModuleColor1TypeValues lists every valid QrDesignConfigModuleColor1Type, in the order oapi-codegen generated them.
var QrDesignConfigModuleColor1TypeValues = []QrDesignConfigModuleColor1Type{
	QrDesignConfigModuleColor1TypeLinear,
	QrDesignConfigModuleColor1TypeRadial,
}

// QrDesignConfigModuleStyleIdValues lists every valid QrDesignConfigModuleStyleId, in the order oapi-codegen generated them.
var QrDesignConfigModuleStyleIdValues = []QrDesignConfigModuleStyleId{
	QrDesignConfigModuleStyleIdArtist,
	QrDesignConfigModuleStyleIdBacteria,
	QrDesignConfigModuleStyleIdBlocky,
	QrDesignConfigModuleStyleIdBlotchy,
	QrDesignConfigModuleStyleIdBotanical,
	QrDesignConfigModuleStyleIdBrixx,
	QrDesignConfigModuleStyleIdBrush,
	QrDesignConfigModuleStyleIdBubbles,
	QrDesignConfigModuleStyleIdCalligraphy,
	QrDesignConfigModuleStyleIdCharacters,
	QrDesignConfigModuleStyleIdChevron,
	QrDesignConfigModuleStyleIdCircuits,
	QrDesignConfigModuleStyleIdClassic,
	QrDesignConfigModuleStyleIdComicFries,
	QrDesignConfigModuleStyleIdConnected,
	QrDesignConfigModuleStyleIdDiamond,
	QrDesignConfigModuleStyleIdDither,
	QrDesignConfigModuleStyleIdDoodle,
	QrDesignConfigModuleStyleIdDoubleBubble,
	QrDesignConfigModuleStyleIdDrip,
	QrDesignConfigModuleStyleIdExplosion,
	QrDesignConfigModuleStyleIdFilm,
	QrDesignConfigModuleStyleIdFireworks,
	QrDesignConfigModuleStyleIdFish,
	QrDesignConfigModuleStyleIdFlourish,
	QrDesignConfigModuleStyleIdGlitch,
	QrDesignConfigModuleStyleIdGrass,
	QrDesignConfigModuleStyleIdHalfmoon,
	QrDesignConfigModuleStyleIdInkPen,
	QrDesignConfigModuleStyleIdIsometric,
	QrDesignConfigModuleStyleIdLeaves,
	QrDesignConfigModuleStyleIdMegaShapes,
	QrDesignConfigModuleStyleIdMosaic,
	QrDesignConfigModuleStyleIdN3d,
	QrDesignConfigModuleStyleIdNeighborAware,
	QrDesignConfigModuleStyleIdOrganic,
	QrDesignConfigModuleStyleIdOverlay,
	QrDesignConfigModuleStyleIdPacman,
	QrDesignConfigModuleStyleIdPaintStrokes,
	QrDesignConfigModuleStyleIdPatchwork,
	QrDesignConfigModuleStyleIdPetals,
	QrDesignConfigModuleStyleIdPhotoOverlay,
	QrDesignConfigModuleStyleIdPizza,
	QrDesignConfigModuleStyleIdPuzzle,
	QrDesignConfigModuleStyleIdRaindrop,
	QrDesignConfigModuleStyleIdRetro,
	QrDesignConfigModuleStyleIdRipple,
	QrDesignConfigModuleStyleIdRotated,
	QrDesignConfigModuleStyleIdRoundedDots,
	QrDesignConfigModuleStyleIdRoundedSquares,
	QrDesignConfigModuleStyleIdSketch,
	QrDesignConfigModuleStyleIdSpiky,
	QrDesignConfigModuleStyleIdSplatter,
	QrDesignConfigModuleStyleIdSpooky,
	QrDesignConfigModuleStyleIdTetris,
	QrDesignConfigModuleStyleIdTriangle,
	QrDesignConfigModuleStyleIdVariedDots,
	QrDesignConfigModuleStyleIdVortex,
	QrDesignConfigModuleStyleIdWashiTape,
	QrDesignConfigModuleStyleIdWavy,
	QrDesignConfigModuleStyleIdWoodwork,
}

// QrDesignConfigPaletteModeValues lists every valid QrDesignConfigPaletteMode, in the order oapi-codegen generated them.
var QrDesignConfigPaletteModeValues = []QrDesignConfigPaletteMode{
	QrDesignConfigPaletteModeCheckerboard,
	QrDesignConfigPaletteModeDiagonal,
	QrDesignConfigPaletteModeGroup,
	QrDesignConfigPaletteModeHorizontal,
	QrDesignConfigPaletteModeLava,
	QrDesignConfigPaletteModeMandala,
	QrDesignConfigPaletteModeNoise,
	QrDesignConfigPaletteModeRadial,
	QrDesignConfigPaletteModeRings,
	QrDesignConfigPaletteModeScatter,
	QrDesignConfigPaletteModeSpiral,
	QrDesignConfigPaletteModeVertical,
	QrDesignConfigPaletteModeWave,
}

// QrDesignConfigPresetValues lists every valid QrDesignConfigPreset, in the order oapi-codegen generated them.
var QrDesignConfigPresetValues = []QrDesignConfigPreset{
	QrDesignConfigPresetArcade,
	QrDesignConfigPresetArchitecture,
	QrDesignConfigPresetAutumn,
	QrDesignConfigPresetBacteria,
	QrDesignConfigPresetBats,
	QrDesignConfigPresetBigFish,
	QrDesignConfigPresetBlocky,
	QrDesignConfigPresetBlotchy,
	QrDesignConfigPresetBoa,
	QrDesignConfigPresetBotanical,
	QrDesignConfigPresetBrixx,
	QrDesignConfigPresetBrushFiesta,
	QrDesignConfigPresetBrushstroke,
	QrDesignConfigPresetBubbles,
	QrDesignConfigPresetCalligraphy,
	QrDesignConfigPresetCandyBlocks,
	QrDesignConfigPresetCarnival,
	QrDesignConfigPresetChristmas,
	QrDesignConfigPresetCircuit,
	QrDesignConfigPresetClassic,
	QrDesignConfigPresetComicBricks,
	QrDesignConfigPresetComicFries,
	QrDesignConfigPresetConnected,
	QrDesignConfigPresetCreeper,
	QrDesignConfigPresetCritters,
	QrDesignConfigPresetCyberpunk,
	QrDesignConfigPresetDarkBush,
	QrDesignConfigPresetDeepBlue,
	QrDesignConfigPresetDeepSea,
	QrDesignConfigPresetDiscoFloor,
	QrDesignConfigPresetDither,
	QrDesignConfigPresetDitherRainbow,
	QrDesignConfigPresetDoodle,
	QrDesignConfigPresetElNino,
	QrDesignConfigPresetElegant,
	QrDesignConfigPresetEscher,
	QrDesignConfigPresetExplosion,
	QrDesignConfigPresetFacebook,
	QrDesignConfigPresetFiesta,
	QrDesignConfigPresetFireworks,
	QrDesignConfigPresetFlorist,
	QrDesignConfigPresetFlourish,
	QrDesignConfigPresetForest,
	QrDesignConfigPresetGalaxy,
	QrDesignConfigPresetGlitched,
	QrDesignConfigPresetGrass,
	QrDesignConfigPresetHalloween,
	QrDesignConfigPresetHandmade,
	QrDesignConfigPresetHypnotic,
	QrDesignConfigPresetIcy,
	QrDesignConfigPresetInkBloom,
	QrDesignConfigPresetInstagram,
	QrDesignConfigPresetLazyArt,
	QrDesignConfigPresetLinkedin,
	QrDesignConfigPresetMidCentury,
	QrDesignConfigPresetMidnight,
	QrDesignConfigPresetMinecraft,
	QrDesignConfigPresetModern,
	QrDesignConfigPresetMorseCode,
	QrDesignConfigPresetMosaic,
	QrDesignConfigPresetNeonDrip,
	QrDesignConfigPresetNewYear,
	QrDesignConfigPresetNickelodeon,
	QrDesignConfigPresetOcean,
	QrDesignConfigPresetOldFilm,
	QrDesignConfigPresetOrganic,
	QrDesignConfigPresetPacman,
	QrDesignConfigPresetPaintSplash,
	QrDesignConfigPresetPaperKoi,
	QrDesignConfigPresetPatchwork,
	QrDesignConfigPresetPetals,
	QrDesignConfigPresetPinwheel,
	QrDesignConfigPresetPurpleChain,
	QrDesignConfigPresetPuzzle,
	QrDesignConfigPresetRainyDay,
	QrDesignConfigPresetRetroTriangle,
	QrDesignConfigPresetRetroWave,
	QrDesignConfigPresetRetroWave70s,
	QrDesignConfigPresetRipple,
	QrDesignConfigPresetSlimer,
	QrDesignConfigPresetStitches,
	QrDesignConfigPresetSummer,
	QrDesignConfigPresetSunset,
	QrDesignConfigPresetSynthwave,
	QrDesignConfigPresetTetris,
	QrDesignConfigPresetTiktok,
	QrDesignConfigPresetTropicalPunch,
	QrDesignConfigPresetValentines,
	QrDesignConfigPresetVernissage,
	QrDesignConfigPresetVinylGroove,
	QrDesignConfigPresetWashiTape,
	QrDesignConfigPresetWhatsapp,
	QrDesignConfigPresetWindswept,
	QrDesignConfigPresetWoodwork,
	QrDesignConfigPresetYoutube,
	QrDesignConfigPresetZigzag,
}

// RegisterKeyJSONBodyLangValues lists every valid RegisterKeyJSONBodyLang, in the order oapi-codegen generated them.
var RegisterKeyJSONBodyLangValues = []RegisterKeyJSONBodyLang{
	De,
	En,
}

// RenderQrCodeParamsBackground1Values lists every valid RenderQrCodeParamsBackground1, in the order oapi-codegen generated them.
var RenderQrCodeParamsBackground1Values = []RenderQrCodeParamsBackground1{
	RenderQrCodeParamsBackground1Transparent,
}

// RenderQrCodeParamsFormatValues lists every valid RenderQrCodeParamsFormat, in the order oapi-codegen generated them.
var RenderQrCodeParamsFormatValues = []RenderQrCodeParamsFormat{
	RenderQrCodeParamsFormatPng,
	RenderQrCodeParamsFormatSvg,
}

// RenderQrCodeParamsPresetValues lists every valid RenderQrCodeParamsPreset, in the order oapi-codegen generated them.
var RenderQrCodeParamsPresetValues = []RenderQrCodeParamsPreset{
	RenderQrCodeParamsPresetArcade,
	RenderQrCodeParamsPresetArchitecture,
	RenderQrCodeParamsPresetAutumn,
	RenderQrCodeParamsPresetBacteria,
	RenderQrCodeParamsPresetBats,
	RenderQrCodeParamsPresetBigFish,
	RenderQrCodeParamsPresetBlocky,
	RenderQrCodeParamsPresetBlotchy,
	RenderQrCodeParamsPresetBoa,
	RenderQrCodeParamsPresetBotanical,
	RenderQrCodeParamsPresetBrixx,
	RenderQrCodeParamsPresetBrushFiesta,
	RenderQrCodeParamsPresetBrushstroke,
	RenderQrCodeParamsPresetBubbles,
	RenderQrCodeParamsPresetCalligraphy,
	RenderQrCodeParamsPresetCandyBlocks,
	RenderQrCodeParamsPresetCarnival,
	RenderQrCodeParamsPresetChristmas,
	RenderQrCodeParamsPresetCircuit,
	RenderQrCodeParamsPresetClassic,
	RenderQrCodeParamsPresetComicBricks,
	RenderQrCodeParamsPresetComicFries,
	RenderQrCodeParamsPresetConnected,
	RenderQrCodeParamsPresetCreeper,
	RenderQrCodeParamsPresetCritters,
	RenderQrCodeParamsPresetCyberpunk,
	RenderQrCodeParamsPresetDarkBush,
	RenderQrCodeParamsPresetDeepBlue,
	RenderQrCodeParamsPresetDeepSea,
	RenderQrCodeParamsPresetDiscoFloor,
	RenderQrCodeParamsPresetDither,
	RenderQrCodeParamsPresetDitherRainbow,
	RenderQrCodeParamsPresetDoodle,
	RenderQrCodeParamsPresetElNino,
	RenderQrCodeParamsPresetElegant,
	RenderQrCodeParamsPresetEscher,
	RenderQrCodeParamsPresetExplosion,
	RenderQrCodeParamsPresetFacebook,
	RenderQrCodeParamsPresetFiesta,
	RenderQrCodeParamsPresetFireworks,
	RenderQrCodeParamsPresetFlorist,
	RenderQrCodeParamsPresetFlourish,
	RenderQrCodeParamsPresetForest,
	RenderQrCodeParamsPresetGalaxy,
	RenderQrCodeParamsPresetGlitched,
	RenderQrCodeParamsPresetGrass,
	RenderQrCodeParamsPresetHalloween,
	RenderQrCodeParamsPresetHandmade,
	RenderQrCodeParamsPresetHypnotic,
	RenderQrCodeParamsPresetIcy,
	RenderQrCodeParamsPresetInkBloom,
	RenderQrCodeParamsPresetInstagram,
	RenderQrCodeParamsPresetLazyArt,
	RenderQrCodeParamsPresetLinkedin,
	RenderQrCodeParamsPresetMidCentury,
	RenderQrCodeParamsPresetMidnight,
	RenderQrCodeParamsPresetMinecraft,
	RenderQrCodeParamsPresetModern,
	RenderQrCodeParamsPresetMorseCode,
	RenderQrCodeParamsPresetMosaic,
	RenderQrCodeParamsPresetNeonDrip,
	RenderQrCodeParamsPresetNewYear,
	RenderQrCodeParamsPresetNickelodeon,
	RenderQrCodeParamsPresetOcean,
	RenderQrCodeParamsPresetOldFilm,
	RenderQrCodeParamsPresetOrganic,
	RenderQrCodeParamsPresetPacman,
	RenderQrCodeParamsPresetPaintSplash,
	RenderQrCodeParamsPresetPaperKoi,
	RenderQrCodeParamsPresetPatchwork,
	RenderQrCodeParamsPresetPetals,
	RenderQrCodeParamsPresetPinwheel,
	RenderQrCodeParamsPresetPurpleChain,
	RenderQrCodeParamsPresetPuzzle,
	RenderQrCodeParamsPresetRainyDay,
	RenderQrCodeParamsPresetRetroTriangle,
	RenderQrCodeParamsPresetRetroWave,
	RenderQrCodeParamsPresetRetroWave70s,
	RenderQrCodeParamsPresetRipple,
	RenderQrCodeParamsPresetSlimer,
	RenderQrCodeParamsPresetStitches,
	RenderQrCodeParamsPresetSummer,
	RenderQrCodeParamsPresetSunset,
	RenderQrCodeParamsPresetSynthwave,
	RenderQrCodeParamsPresetTetris,
	RenderQrCodeParamsPresetTiktok,
	RenderQrCodeParamsPresetTropicalPunch,
	RenderQrCodeParamsPresetValentines,
	RenderQrCodeParamsPresetVernissage,
	RenderQrCodeParamsPresetVinylGroove,
	RenderQrCodeParamsPresetWashiTape,
	RenderQrCodeParamsPresetWhatsapp,
	RenderQrCodeParamsPresetWindswept,
	RenderQrCodeParamsPresetWoodwork,
	RenderQrCodeParamsPresetYoutube,
	RenderQrCodeParamsPresetZigzag,
}

// RenderQrCodeWithDesignJSONBodyFormatValues lists every valid RenderQrCodeWithDesignJSONBodyFormat, in the order oapi-codegen generated them.
var RenderQrCodeWithDesignJSONBodyFormatValues = []RenderQrCodeWithDesignJSONBodyFormat{
	RenderQrCodeWithDesignJSONBodyFormatPng,
	RenderQrCodeWithDesignJSONBodyFormatSvg,
}
