package main

import (
	"go/format"
	"strings"
	"testing"
)

func TestGenerateEnumValues(t *testing.T) {
	src := `// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

const (
	INTERNALERROR ErrorCode = "INTERNAL_ERROR"
	NOTFOUND      ErrorCode = "NOT_FOUND"
)

type ErrorCode string

const (
	QrDesignConfigPresetArcade QrDesignConfigPreset = "arcade"
	QrDesignConfigPresetOcean  QrDesignConfigPreset = "ocean"
)

type QrDesignConfigPreset string

// Not an enum: a single untyped const, should be ignored rather than crash.
const SomethingElse = 42
`
	formatted, err := format.Source([]byte(src))
	if err != nil {
		t.Fatalf("test fixture doesn't parse as Go: %v", err)
	}

	out, err := generateEnumValues(formatted)
	if err != nil {
		t.Fatalf("generateEnumValues: %v", err)
	}
	got := string(out)

	for _, want := range []string{
		"var ErrorCodeValues = []ErrorCode{\n\tINTERNALERROR,\n\tNOTFOUND,\n}",
		"var QrDesignConfigPresetValues = []QrDesignConfigPreset{\n\tQrDesignConfigPresetArcade,\n\tQrDesignConfigPresetOcean,\n}",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("output missing expected block:\n%s\n\nfull output:\n%s", want, got)
		}
	}
	if strings.Contains(got, "SomethingElse") {
		t.Errorf("non-enum const leaked into output:\n%s", got)
	}

	// The output itself must be valid, already-formatted Go — generateEnumValues runs
	// format.Source before returning, so a second pass should be a no-op.
	reformatted, err := format.Source(out)
	if err != nil {
		t.Fatalf("generated output is not valid Go: %v", err)
	}
	if string(reformatted) != got {
		t.Error("generateEnumValues's output is not already gofmt-formatted")
	}
}

func TestGenerateEnumValues_deterministicTypeOrder(t *testing.T) {
	src := `package openapi

const (
	Zebra ZType = "z"
)

type ZType string

const (
	Apple AType = "a"
)

type AType string
`
	formatted, err := format.Source([]byte(src))
	if err != nil {
		t.Fatalf("test fixture doesn't parse as Go: %v", err)
	}

	out, err := generateEnumValues(formatted)
	if err != nil {
		t.Fatalf("generateEnumValues: %v", err)
	}
	got := string(out)

	aIdx := strings.Index(got, "ATypeValues")
	zIdx := strings.Index(got, "ZTypeValues")
	if aIdx == -1 || zIdx == -1 {
		t.Fatalf("expected both ATypeValues and ZTypeValues in output:\n%s", got)
	}
	if aIdx > zIdx {
		t.Errorf("expected ATypeValues (alphabetically first) before ZTypeValues, got them in the other order")
	}
}
